In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/league-of-legends-diamond-ranked-games-10-min/high_diamond_ranked_10min.csv

In [3]:
hdr1 = pd.read_csv(os.path.join(dirname, filename))

hdr1.head()

,gameId,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,...,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
0,4519157822,0,28,2,1,9,6,11,0,0,...,0,16567,6.8,17047,197,55,-643,8,19.7,1656.7
1,4523371949,0,12,1,0,5,5,5,0,0,...,1,17620,6.8,17438,240,52,2908,1173,24.0,1762.0
2,4521474530,0,15,0,0,7,11,4,1,1,...,0,17285,6.8,17254,203,28,1172,1033,20.3,1728.5
3,4524384067,0,43,1,0,4,5,5,1,0,...,0,16478,7.0,17961,235,47,1321,7,23.5,1647.8
4,4436033771,0,75,4,0,6,6,6,0,0,...,0,17404,7.0,18313,225,67,1004,-230,22.5,1740.4

In [9]:
hdr1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9879 entries, 0 to 9878
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   gameid                        9879 non-null   int64
 1   bluewins                      9879 non-null   int64
 2   bluewardsplaced               9879 non-null   int64
 3   bluewardsdestroyed            9879 non-null   int64
 4   bluefirstblood                9879 non-null   int64
 5   bluekills                     9879 non-null   int64
 6   bluedeaths                    9879 non-null   int64
 7   blueassists                   9879 non-null   int64
 8   blueelitemonsters             9879 non-null   int64
 9   bluedragons                   9879 non-null   int64
 10  blueheralds                   9879 non-null   int64
 11  bluetowersdestroyed           9879 non-null   int64
 12  bluetotalgold                 9879 non-null   int64
 13  blueavglevel                  9879 non-null   float64
 14  bluetotalexperience           9879 non-null   int64
 15  bluetotalminionskilled        9879 non-null   int64
 16  bluetotaljungleminionskilled  9879 non-null   int64
 17  bluegolddiff                  9879 non-null   int64
 18  blueexperiencediff            9879 non-null   int64
 19  bluecspermin                  9879 non-null   float64
 20  bluegoldpermin                9879 non-null   float64
 21  redwardsplaced                9879 non-null   int64
 22  redwardsdestroyed             9879 non-null   int64
 23  redfirstblood                 9879 non-null   int64
 24  redkills                      9879 non-null   int64
 25  reddeaths                     9879 non-null   int64
 26  redassists                    9879 non-null   int64
 27  redelitemonsters              9879 non-null   int64
 28  reddragons                    9879 non-null   int64
 29  redheralds                    9879 non-null   int64
 30  redtowersdestroyed            9879 non-null   int64
 31  redtotalgold                  9879 non-null   int64
 32  redavglevel                   9879 non-null   float64
 33  redtotalexperience            9879 non-null   int64
 34  redtotalminionskilled         9879 non-null   int64
 35  redtotaljungleminionskilled   9879 non-null   int64
 36  redgolddiff                   9879 non-null   int64
 37  redexperiencediff             9879 non-null   int64
 38  redcspermin                   9879 non-null   float64
 39  redgoldpermin                 9879 non-null   float64
dtypes: float64(6), int64(34)
memory usage: 3.0 MB

In [5]:
hdr1.columns = hdr1.columns.str.lower()

In [16]:
hdr2 = hdr1[{"bluewins","bluefirstblood","bluekills","redkills","bluewardsplaced","redwardsplaced","blueelitemonsters","redelitemonsters","bluetowersdestroyed","redtowersdestroyed","bluegolddiff","bluecspermin","redcspermin"}]

In [17]:
hdr2.head()

,bluekills,blueelitemonsters,redcspermin,bluewardsplaced,redkills,bluecspermin,redtowersdestroyed,bluegolddiff,bluefirstblood,redwardsplaced,bluewins,bluetowersdestroyed,redelitemonsters
0,9,0,19.7,28,6,19.5,0,643,1,15,0,0,0
1,5,0,24.0,12,5,17.4,1,-2908,0,12,0,0,2
2,7,1,20.3,15,11,18.6,0,-1172,0,15,0,0,0
3,4,1,23.5,43,5,20.1,0,-1321,0,15,0,0,0
4,6,0,22.5,75,6,21.0,0,-1004,0,17,0,0,1

In [22]:
plt.figure(figsize=(20,15))
sns.heatmap(hdr2.corr(), annot=True, cmap='coolwarm', fmt='.2g')

ValueError: 'bluegreen' is not a valid value for name; supported values are 'Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r', 'Greens', 'Greens_r', 'Greys', 'Greys_r', 'OrRd', 'OrRd_r', 'Oranges', 'Oranges_r', 'PRGn', 'PRGn_r', 'Paired', 'Paired_r', 'Pastel1', 'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn', 'PuBuGn_r', 'PuBu_r', 'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples', 'Purples_r', 'RdBu', 'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu', 'RdYlBu_r', 'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r', 'Set2', 'Set2_r', 'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia', 'Wistia_r', 'YlGn', 'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r', 'YlOrRd', 'YlOrRd_r', 'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'binary', 'binary_r', 'bone', 'bone_r', 'brg', 'brg_r', 'bwr', 'bwr_r', 'cividis', 'cividis_r', 'cool', 'cool_r', 'coolwarm', 'coolwarm_r', 'copper', 'copper_r', 'cubehelix', 'cubehelix_r', 'flag', 'flag_r', 'gist_earth', 'gist_earth_r', 'gist_gray', 'gist_gray_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r', 'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r', 'gist_yarg', 'gist_yarg_r', 'gnuplot', 'gnuplot2', 'gnuplot2_r', 'gnuplot_r', 'gray', 'gray_r', 'hot', 'hot_r', 'hsv', 'hsv_r', 'icefire', 'icefire_r', 'inferno', 'inferno_r', 'jet', 'jet_r', 'magma', 'magma_r', 'mako', 'mako_r', 'nipy_spectral', 'nipy_spectral_r', 'ocean', 'ocean_r', 'pink', 'pink_r', 'plasma', 'plasma_r', 'prism', 'prism_r', 'rainbow', 'rainbow_r', 'rocket', 'rocket_r', 'seismic', 'seismic_r', 'spring', 'spring_r', 'summer', 'summer_r', 'tab10', 'tab10_r', 'tab20', 'tab20_r', 'tab20b', 'tab20b_r', 'tab20c', 'tab20c_r', 'terrain', 'terrain_r', 'twilight', 'twilight_r', 'twilight_shifted', 'twilight_shifted_r', 'viridis', 'viridis_r', 'vlag', 'vlag_r', 'winter', 'winter_r'